/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 baman.gltf --transform
Author: CAPTAAINR (https://sketchfab.com/CAPTAAINR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/batman-textured-rigged-047eabea3b4f48f5bc179c48bf72b7b0
Title: BATMAN (Textured) (Rigged)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/baman-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model001_Material001} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model001_Material001} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model001_Material001} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model001_Material004} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model001_Material005} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Model001_Material006} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Model001_Material007} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Model001_Material008} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Model001_Material009} />
      </group>
    </group>
  )
}

useGLTF.preload('/baman-transformed.glb')
