/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 imac.gltf --transform
Author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imac-3d-model-free-agustin-honnun-e632ef53df614e30b9983089ff984fa4
Title: iMac 3D Model | [FREE] | Agustin Honnun
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/imac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 6.27, 2.8]} scale={0.04}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Display_iMac_0.geometry} material={materials.iMac} position={[2.68, 83.16, 64.78]} rotation={[-1.48, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Base_Base_0.geometry} material={materials.Base} position={[2.68, -0.12, 67.89]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Keyboard_Keyboard_0.geometry} material={materials.Keyboard} position={[22.16, 1.57, -0.48]} rotation={[-1.58, 0, 3.14]} scale={100} />
          <mesh geometry={nodes.Mouse001_Mouse_0.geometry} material={materials.Mouse} position={[-49.73, 1.05, 2.46]} rotation={[-Math.PI / 2, 0, 0.02]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/imac-transformed.glb')
