/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 iphone2.gltf --transform
Author: fiedleradam358 (https://sketchfab.com/fiedleradam358)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-max-blend-e5adbbffa58f493bad362a9d1f0dc43d
Title: iPhone 14 Max (Blend)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2.2, 6.27, 3.5]}>
        <group position={[0.25, -0.19, -1.95]} scale={[0.02, 0.01, 0.02]}>
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-0.5, 0.02, -1.58]} scale={0.38}>
          <mesh geometry={nodes.Object_18.geometry} material={materials.Back_Glass} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Body} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['Material.007']} />
        </group>
        <group position={[-0.66, 0, -1.74]} scale={[0.05, 0.03, 0.05]}>
          <mesh geometry={nodes.Object_23.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Body} />
          <mesh geometry={nodes.Object_25.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_27.geometry} material={materials['Material.005']} />
        </group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Back_Glass} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Body} position={[-0.96, -0.1, -0.71]} rotation={[0, 0, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/iphone2-transformed.glb')
